### ISSUE TITLE
Error received when launching GraphiQL 

### ISSUE THREAD

**Issue by duffn** [leighhalliday/landbnb#1]
I receive this error when launching GraphiQL in the browser at http://localhost:3000/graphiql. I am not attempting to execute any query, but just launching GraphiQL.
```
SyntaxError: Unexpected token < in JSON at position 0
```
In the console
```
% rails s
=> Booting Puma
=> Rails 5.1.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/graphiql" for 127.0.0.1 at 2017-08-31 08:38:59 -0600
   (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by GraphiQL::Rails::EditorsController#show as HTML
  Parameters: {"graphql_path"=>"/graphql"}
  Rendering /Users/nicholasduffy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphiql-rails-1.4.2/app/views/graphiql/rails/editors/show.html.erb
  Rendered /Users/nicholasduffy/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/graphiql-rails-1.4.2/app/views/graphiql/rails/editors/show.html.erb (184.7ms)
Completed 200 OK in 200ms (Views: 192.9ms | ActiveRecord: 0.0ms)


Started POST "/graphql" for 127.0.0.1 at 2017-08-31 08:39:00 -0600
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n", "graphql"=>{"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"}}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)



ArgumentError (invalid base64):

app/models/auth_token.rb:12:in `verify'
app/controllers/graphql_controller.rb:26:in `current_user'
app/controllers/graphql_controller.rb:9:in `execute'
```
Environment
```
% rails -v
Rails 5.1.3
% ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
```

**Comment by karloespiritu** [comment]
I got the same exact error as well on initial load of `/graphiql'`url . I'm also using the same Rails/Ruby environment.

**Comment by leighhalliday** [comment]
Hmm... good questions... and sorry for the delay responding.

I **think** it is because there is no environment variable named JWT_TOKEN. I have a `.env` file for developing locally and am storing it there.

To generate this token for a user you can run this command: `AuthToken.token(User.last)`

Let me know if that helps!

**Comment by ChrisChinchilla** [comment]
@leighhalliday Run that command where?

**Comment by duffn** [comment]
Yes, this works. I have created a PR to update the README: https://github.com/leighhalliday/landbnb/pull/2
